### ISSUE TITLE
Uninstall unneeded programs

### ISSUE THREAD

**Issue by trikon** [cowboy/dotfiles#48]
Cowboy please tell me, how i can remove programs installed with your .dotfiles?
Ex: ReaMote64, REAPER64, Moom...etc

**Comment by cowboy** [comment]
I have some info in the README about how to maintain your own fork of this repo. That will allow you do upstream changes only as you need.

https://github.com/cowboy/dotfiles#heed-this-critically-important-warning-before-you-install
