### ISSUE TITLE
automatic execution of files in "source"

### ISSUE THREAD

**Issue by nnako** [cowboy/dotfiles#58]
Hi,

**thank you** for your great scripts and configurations, and the proposed concept of managing them. I am currently using a small subset of the folders (init, copy and link) in order to setup Raspbian systems. It works great.

**Just one question I have**: Although the files within the subfolders COPY, LINK and INIT are handled as expected, the files in the SOURCE subfolder seem not to be. For example, I would like to see the prompt change according to the file `source/50_prompt.sh` . As the file `bin/dotfiles` does not execute / handle the SOURCE files as done for COPY, LINK and INIT, **where (in which of the repository files) do I find the line of code which executes them?**

Thank you very much.

**Comment by cowboy** [comment]
https://github.com/cowboy/dotfiles/blob/master/link/.bashrc
